export class Constants {
  static readonly pathService = 'http://localhost:55451/api';

  static readonly localeText = {
    page: 'Pagina',
    more: 'Mas',
    to: 'a',
    of: 'de',
    next: 'Siguiente',
    last: 'Ultimo',
    first: 'Primero',
    previous: 'Anterior',
    loadingOoo: 'Cargando...',
    selectAll: 'Seleccionar Todo',
    searchOoo: 'Buscando...',
    blanks: 'En Blanco',
    filterOoo: 'Filtrando...',
    applyFilter: 'Aplicar Filtro...',
    equals: 'Iguales',
    notEqual: 'Desiguales',
    lessThan: 'Menor que',
    greaterThan: 'Mayor que',
    lessThanOrEqual: 'Menor o Igual',
    greaterThanOrEqual: 'Mayor o Igual',
    inRange: 'En el rango',
    contains: 'Contenga',
    notContains: 'No Contenga',
    startsWith: 'Comienza con',
    endsWith: 'Termina con',
    andCondition: 'Y',
    orCondition: 'O',
    group: 'Grupo',
    columns: 'Columnas',
    filters: 'Filtros',
    rowGroupColumns: 'Grupo de Filas y Columnas',
    rowGroupColumnsEmptyMessage: 'Arrastrar columnas',
    valueColumns: 'Valor de la Columna',
    pivotMode: 'Modo Pivote',
    groups: 'Grupos',
    values: 'Valores',
    pivots: 'Pivots',
    valueColumnsEmptyMessage: 'Arrastrar y Agregar',
    pivotColumnsEmptyMessage: 'Arrastrar para Pivotar',
    toolPanelButton: 'Panel de Herramientas',
    noRowsToShow: 'Sin Filas',
    pinColumn: 'Pin Clumn',
    valueAggregation: 'laValue Agg',
    autosizeThiscolumn: 'laAutosize Diz',
    autosizeAllColumns: 'laAutsoie em All',
    groupBy: 'laGroup by',
    ungroupBy: 'laUnGroup by',
    resetColumns: 'Reestablecer Columnas',
    expandAll: 'Expandir todo',
    collapseAll: 'Contraer Todo',
    toolPanel: 'laTool Panelo',
    export: 'Exportar',
    csvExport: 'Exportar a CSV',
    excelExport: 'Exportar a Excel (.xlsx)',
    excelXmlExport: 'Exportar a Excel XML (.xml)',
    pinLeft: 'laPin &lt;&lt;',
    pinRight: 'laPin &gt;&gt;',
    noPin: 'laDontPin &lt;&gt;',
    sum: 'laSum',
    min: 'laMin',
    max: 'laMax',
    none: 'laNone',
    count: 'laCount',
    average: 'laAverage',
    copy: 'laCopy',
    copyWithHeaders: 'laCopy Wit hHeaders',
    ctrlC: 'ctrl n C',
    paste: 'laPaste',
    ctrlV: 'ctrl n V'
  };
}
